#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_protocol_cli
pushd _test_protocol_cli

../scripts/setup_config_file.sh

aut protocol config
aut protocol epoch-id
aut protocol last-epoch-time
aut protocol epoch-total-bonded-stake
aut protocol inflation-reserve
aut protocol current-epoch-period
aut protocol epoch-period
aut protocol block-period
aut protocol unbonding-period
aut protocol last-epoch-block
aut protocol version
aut protocol committee
aut protocol validators
aut protocol treasury-account
aut protocol treasury-fee
aut protocol current-committee-size
aut protocol max-committee-size
aut protocol committee-enodes
aut protocol minimum-base-fee
aut protocol operator
aut protocol contract-address
aut protocol contract-abi
aut protocol epoch-from-block 1
aut protocol max-schedule-duration
aut protocol total-schedules 0x0000000000000000000000000000000000000000
aut protocol epoch-info
aut protocol epoch-by-height 0
aut protocol is-unbonding-released 0

# Reverts if there is no unbonding
aut protocol unbonding-share --help >/dev/null

# Reverts if there is no schedule
aut protocol schedule --help >/dev/null

set +e
set +x

popd
