#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_governance_cli
pushd _test_governance_cli

../scripts/setup_config_file.sh

# Test help text (does some parameter validation)
aut governance set-committee-size --help > /dev/null
aut governance set-unbonding-period --help > /dev/null
aut governance set-epoch-period --help > /dev/null
aut governance set-operator-account --help > /dev/null
aut governance set-treasury-account --help > /dev/null
aut governance set-treasury-fee --help > /dev/null
aut governance set-accountability-contract --help > /dev/null
aut governance set-oracle-contract --help > /dev/null
aut governance set-acu-contract --help > /dev/null
aut governance set-supply-control-contract --help > /dev/null
aut governance set-stabilization-contract --help > /dev/null
aut governance set-inflation-controller-contract --help > /dev/null
aut governance set-omission-accountability-contract --help > /dev/null
aut governance set-liquid-logic-contract --help > /dev/null
aut governance set-auctioneer-contract --help > /dev/null
aut governance set-upgrade-manager-contract --help > /dev/null
aut governance set-max-schedule-duration --help > /dev/null
aut governance set-oracle-reward-rate --help > /dev/null
aut governance set-proposer-reward-rate --help > /dev/null
aut governance set-slasher --help > /dev/null
aut governance set-withholding-threshold --help > /dev/null
aut governance set-withheld-rewards-pool --help > /dev/null
aut governance set-eip1559-params --help > /dev/null
aut governance create-schedule --help > /dev/null
aut governance mint --help > /dev/null
aut governance burn --help > /dev/null

set +e
set +x

popd
