#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_protocol_cli
pushd _test_protocol_cli

../scripts/setup_config_file.sh

aut protocol config
aut protocol epoch-id
aut protocol last-epoch-time
aut protocol epoch-total-bonded-stake
aut protocol inflation-reserve
aut protocol deployer
aut protocol epoch-period
aut protocol block-period
aut protocol unbonding-period
aut protocol last-epoch-block
aut protocol version
aut protocol committee
aut protocol validators
aut protocol treasury-account
aut protocol treasury-fee
aut protocol max-committee-size
aut protocol committee-enodes
aut protocol minimum-base-fee
aut protocol operator
aut protocol contract-address
aut protocol epoch-from-block 1

set +e
set +x

popd
