#!/usr/bin/env bash

set -x
set -e

mkdir -p _test_governance_cli
pushd _test_governance_cli

../scripts/setup_config_file.sh

# Test help text (does some parameter validation)
aut governance set-minimum-base-fee --help > /dev/null
aut governance set-committee-size --help > /dev/null
aut governance set-unbonding-period --help > /dev/null
aut governance set-epoch-period --help > /dev/null
aut governance set-operator-account --help > /dev/null
aut governance set-treasury-account --help > /dev/null
aut governance set-treasury-fee --help > /dev/null
aut governance set-accountability-contract --help > /dev/null
aut governance set-oracle-contract --help > /dev/null
aut governance set-acu-contract --help > /dev/null
aut governance set-supply-control-contract --help > /dev/null
aut governance set-stabilization-contract --help > /dev/null
aut governance set-inflation-controller-contract --help > /dev/null
aut governance set-upgrade-manager-contract --help > /dev/null
aut governance mint --help > /dev/null
aut governance burn --help > /dev/null

set +e
set +x

popd
