name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  HOMEBREW_PACKAGES: "pidof"
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-ver: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-ver }}
      - name: MacOS dependencies
        if: matrix.os == 'macos-11'
        run: |
          brew install ${HOMEBREW_PACKAGES}
      - name: Install hatch
        run: |
          pip install --upgrade hatch
      - name: Lint
        run: hatch run lint:all
      - name: Test
        run: hatch run test
